apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.config.consumerParket.name }}
  labels:
    app: {{ .Values.config.consumerParket.name }}
spec:
  replicas: {{ .Values.config.consumerParket.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.config.consumerParket.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.config.consumerParket.name }}
    spec:
      containers:
        - name: {{ .Values.config.consumerParket.name }}
          image: {{ .Values.config.docker_registry }}/{{ .Values.config.consumerParket.image }}
          env:
            - name: DATAFROMK8S
              value: "Hey"
            - name: RABBITMQ
              value: "databases-rabbitmq"
            - name: RABBITMQ_QUEUE
              value: "queue_parket"
            - name: RABBITMQ_USER
              value: "user"
            - name: XPATH
              value: "/data"
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: databases-rabbitmq
                  key: rabbitmq-password
                  optional: false
            - name: MARIADB
              value: "databases-mariadb"
            - name: MARIADB_TABLE
              value: "objects"
            - name: MARIADB_TABLE_BOOKS
              value: "books"
            - name: MARIADB_TABLE_REVIEWS
              value: "reviews"
            - name: MARIADB_TABLE_PENDING
              value: "pending_review_links"
            - name: MARIADB_DB
              value: "promptsy"
            - name: MARIADB_USER
              value: "root"
            - name: MARIADB_PASS
              valueFrom:
                secretKeyRef:
                  name: databases-mariadb
                  key: mariadb-root-password
                  optional: false
            - name: ELASTIC_USER
              value: "elastic"
            - name: ELASTIC_PASS
              valueFrom:
                secretKeyRef:
                  name: ic4302-es-elastic-user
                  key: elastic
                  optional: false
            - name: ELASTIC_HOST
              value: "ic4302-es-http"
            - name: ELASTIC_INDEX_REVIEWS
              value: "reviews"
            - name: ELASTIC_INDEX_NREVIEWS
              value: "nreviews"
            - name: AWS_BUCKET
              value: "ic-tec-dataset"
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret    
                  key: AWS_ACCESS_KEY
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: AWS_SECRET_KEY
            - name: AWS_REGION
              value: "us-east-1"
            - name: EMBEDDINGENDPOINT
              value: "http://huggingface:5000/encode"
          volumeMounts:
            - name: data-volume
              mountPath: /data
      volumes:
        - name: data-volume
          emptyDir: {}

