{{- if .Values.config.producer.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.config.producer.name }}
spec:
  schedule: {{ .Values.config.producer.schedule}}
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          terminationGracePeriodSeconds: 0
          restartPolicy: OnFailure
          containers:
            - name: {{ .Values.config.producer.name }}
              image: bitnamilegacy/rabbitmq:3.12.12-debian-11-r15
              env:
                - name: S3_BUCKET
                  value: "ic-tec-dataset"
                - name: S3_PREFIXES
                  value: "amazon-books,amazon-book-reviews"
                - name: AWS_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: aws-secret
                      key: AWS_ACCESS_KEY
                      optional: false
                - name: AWS_SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: aws-secret
                      key: AWS_SECRET_KEY
                      optional: false
                - name: AWS_REGION
                  value: "us-east-1"

                - name: RABBITMQ
                  value: "databases-rabbitmq"
                - name: RABBITMQ_QUEUE
                  value: "queue_csv"
                - name: RABBITMQ_QUEUE_PARKET
                  value: "queue_parket"
                - name: RABBITMQ_USER
                  value: "user"
                - name: RABBITMQ_PASS
                  valueFrom:
                    secretKeyRef:
                      name: databases-rabbitmq
                      key: rabbitmq-password
                      optional: false
{{- end }}
