{{- if .Values.config.producer.enabled }}
# Service para exponer métricas
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.config.producer.name }}-metrics
  labels:
    app: {{ .Values.config.producer.name }}
spec:
  selector:
    app: {{ .Values.config.producer.name }}
  ports:
    - name: metrics
      port: 8000
      targetPort: 8000
---
# ServiceMonitor para Prometheus
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.config.producer.name }}-monitor
  namespace: monitoring
  labels:
    release: prometheus
    app: {{ .Values.config.producer.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.config.producer.name }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
{{- end }}