{{ if .Values.config.dataseeder.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.config.dataseeder.name }}
  labels:
    app: {{ .Values.config.dataseeder.name }}
spec:
  template:
    metadata:
      labels:
        app: {{ .Values.config.dataseeder.name }}
    spec:
      restartPolicy: Never
      containers:
      - name: {{ .Values.config.dataseeder.name }}
        image: {{ .Values.config.dataseeder.image }}
        command: 
          - "python"
          - "app.py"
        env:
          {{- if .Values.config.dataseeder.postgresEnable }}
          - name: POSTGRES
            value: "databases-postgresql"
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_DB
            value: "postgres"
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: databases-postgresql
                key: postgres-password
                optional: false
          {{- end }}

          {{- if .Values.config.dataseeder.mariaDBEnable }}
          - name: MARIADB
            value: "databases-mariadb"
          - name: MARIADB_TABLE
            value: "objects"
          - name: MARIADB_DB
            value: "control"
          - name: MARIADB_USER
            value: "root"
          - name: MARIADB_PASS
            valueFrom:
              secretKeyRef:
                name: databases-mariadb
                key: mariadb-root-password
                optional: false
          {{- end }}

          - name: PROMETHEUSENDPOINT
            value: "http://prometheus-operated.monitoring.svc.cluster.local:9090"

          {{- if .Values.config.dataseeder.elasticSearchEnable }}
          - name: ELASTIC_USER
            value: "elastic"
          - name: ES_PORT
            value: "9200"
          - name: ELASTIC_PASS
            valueFrom:
              secretKeyRef:
                name: ic4302-es-elastic-user
                key: elastic
                optional: false
          - name: ELASTIC
            value: "ic4302-es-http"
          {{- end }}

          {{- if .Values.config.dataseeder.chromaDBEnable }}
          - name: CHROMA_ENDPOINT
            value: "http://databases-chromadb:8000"
          - name: CHROMA_COLLECTION
            value: "animals"
          - name: CHROMA_EMBED_MODEL
            value: "sentence-transformers/all-MiniLM-L6-v2"
          {{- end }}

          {{- if .Values.config.dataseeder.openSearchEnable }}
          - name: OPENSEARCH_ENDPOINT
            value: "https://opensearch-cluster-master:9200"
          - name: OPENSEARCH_USER
            value: "admin"
          - name: OPENSEARCH_PASS
            value: "BaseDatos12345!"
          {{- end }}

          {{- if .Values.config.dataseeder.mongoEnable }}
          - name: MONGO_HOST
            value: "databases-mongodb"
          - name: MONGO_PORT
            value: "27017"
          - name: MONGO_DB
            value: "animalsdb"
          - name: MONGO_COLLECTION
            value: "animals"
          - name: MONGO_USER
            value: "root"
          - name: MONGO_PASS
            valueFrom:
              secretKeyRef:
                name: databases-mongodb
                key: mongodb-root-password
                optional: false
          - name: MONGO_AUTH_DB
            value: "admin"
          {{- end }}



          {{- if .Values.config.dataseeder.couchDBEnable }}
          - name: COUCHDB_HOST
            value: "databases-couchdb"
          - name: COUCHDB_PORT
            value: "5984"
          - name: COUCHDB_USER
            value: "admin"
          - name: COUCHDB_PASS
            valueFrom:
              secretKeyRef:
                name: databases-couchdb
                key: adminPassword
          - name: COUCHDB_DB
            value: "animalsdb"
          {{- end }}

          {{- if .Values.config.dataseeder.neo4jEnable }}
          - name: NEO4J_HOST
            value: "databases-neo4j"
          - name: NEO4J_PORT
            value: "7687"
          - name: NEO4J_USER
            value: "neo4j"
          - name: NEO4J_PASS
            valueFrom:
              secretKeyRef:
                name: databases-neo4j
                key: neo4j-password
                optional: false
          - name: NEO4J_DB
            value: "neo4j"
          {{- end }}

          
          - name: NEO4J_ENABLE
            value: "{{ .Values.config.dataseeder.neo4jEnable }}"
          - name: POSTGRES_ENABLE
            value: "{{ .Values.config.dataseeder.postgresEnable }}"
          - name: MARIADB_ENABLE
            value: "{{ .Values.config.dataseeder.mariaDBEnable }}"
          - name: ELASTICSEARCH_ENABLE
            value: "{{ .Values.config.dataseeder.elasticSearchEnable }}"
          - name: OPENSEARCH_ENABLE
            value: "{{ .Values.config.dataseeder.openSearchEnable }}"
          - name: COUCHDB_ENABLE
            value: "{{ .Values.config.dataseeder.couchDBEnable }}"
          - name: CHROMADB_ENABLE
            value: "{{ .Values.config.dataseeder.chromaDBEnable }}"
          - name: MONGO_ENABLE
            value: "{{ .Values.config.dataseeder.mongoEnable }}"

{{ end }}