elastic:
  enabled: true
  version: 8.6.1
  replicas: 1
  name: ic4302
kibana:
  enabled: true
  version: 8.6.1
  replicas: 1
  name: ic4302
mariadb:
  enabled: true
  auth:
    database: "promptsy"
  initdbScriptsConfigMap: "configmap-initdb"
  metrics:
    enabled: false
    serviceMonitor:
      enabled: false
      namespace: "monitoring"

rabbitmq:
  enabled: true
  image:
    registry: docker.io
    repository: bitnamilegacy/rabbitmq
    tag: 3.12.12-debian-11-r15
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: "monitoring"
      
memcached:
  enabled: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: "monitoring"
