elastic:
  enabled: true
  version: 8.6.1
  replicas: 1
  name: ic4302
kibana:
  enabled: true
  version: 8.6.1
  replicas: 1
  name: ic4302
mariadb:
  enabled: true
  auth:
    database: "promptsy"
  initdbScriptsConfigMap: "configmap-initdb"
  metrics:
    enabled: false
    serviceMonitor:
      enabled: false
      namespace: "monitoring"

rabbitmq:
  enabled: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: "monitoring"
memcached:
  enabled: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: "monitoring"

  # Keep this line if you are using Mac OS
  # platform: linux/arm64