config:
  docker_registry: carayacn # docker registry replace with your own username
  producer:
    replicas: 1
    name: s3-crawler
    image: s3-crawler
    schedule: "0 */12 * * *" # every 12 hours
  consumer:
    replicas: 1
    name: ingest
    image: ingest
  debug:
    replicas: 1
    name: debug
    image: s3-crawler
  huggingface:
    replicas: 1
    name: huggingface
    image: huggingface