config:
  docker_registry: prosoli # docker registry replace with your own username
  producer:
    enabled: true
    replicas: 1
    name: s3-crawler
    image: s3-crawler
    schedule: "0 * * * *"  #every hour
  consumer:
    replicas: 1
    name: ingest
    image: ingest
  debug:
    replicas: 1
    name: debug
    image: s3-crawler
  huggingface:
    enabled: true
    replicas: 2 # it is asked to have at least 2 replicas
    name: huggingface
    image: huggingface