prometheus: 
  namespace: monitoring
dashboards:
  elasticsearch:
    name: elasticsearch
    file: elasticsearch.json
    enable: true
  redis:
    name: redis
    file: redis.json
    enable: false
  mariadb:
    name: mariadb
    file: mariadb.json
    enable: false
  mongodb:
    name: mongodb
    file: mongodb.json
    enable: false
  memcached:
    name: memcached
    file: memcached.json
    enable: true
  postgresql:
    name: postgresql
    file: postgresql.json
    enable: false
  chroma:
    name: chroma
    file: chroma.json
    enable: false
  vespa:
    name: vespa
    file: vespa.json
    enable: false
