{{ if .Values.elastic.enabled }}
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{ .Values.elastic.name }}
spec:
  version: {{ .Values.elastic.version }}
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  nodeSets:
  - name: master
    count: {{ .Values.elastic.masterReplicas }}
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms512m -Xmx512m"  #Menor consumo de ram al iniciar elastic
          resources:
            requests:
              #memory: 2Gi
              memory: 700Mi
              #cpu: 1
              cpu: 500m
            limits:
              #memory: 2Gi
              memory: 1500Mi
    config:
      node.store.allow_mmap: false
      node.roles: ["master"]
  - name: data-node
    count: {{ .Values.elastic.replicas }}
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms512m -Xmx512m" #Menor consumo de ram
          resources:
            requests:
              #memory: 2Gi
              memory: 700Mi
              #cpu: 1
              cpu: 500m
            limits:
              #memory: 2Gi
              memory: 1500Mi
    config:
      node.store.allow_mmap: false
      node.roles: ["data"]
{{ end }}