apiVersion: v1
kind: Service
metadata:
  name: vespa-metrics
  namespace: default
  labels:
    app: vespa
spec:
  selector:
    app: vespa
  ports:
    - name: metrics
      port: 19071
      targetPort: 19071
