{
 "title": "Vespa Sistema",
 "description": "Vespa engine dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheusSource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Vespa QRS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP Latency (one minute average/max)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "vespa_container_server_total_successful_response_latency{aggregation=~\"max|average\"}",
     "legendFormat": "{{ host }} {{ aggregation }}"
    }
   ]
  },
  {
   "title": "HTTP requests per second (one minute average)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(vespa_container_server_num_requests{aggregation=\"rate\"}) by (host)",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Query latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vespa_container_query_latency{aggregation=~\"average|min|max|.*percentile\"}",
     "legendFormat": "{{ host }} {{ chain }} {{ aggregation  }}"
    }
   ]
  },
  {
   "title": "Application errors",
   "type": "graph",
   "description": "Application errors on container nodes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (__name__) ({__name__=~\"vespa_container_error.*|vespa_container_rendering_errors\", aggregation=\"rate\"})",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Soft Timeouts",
   "type": "graph",
   "description": "Soft timeouts during ranking\nThese may still return partial results.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (documenttype) (vespa_searchnode_content_proton_documentdb_matching_soft_doomed_queries{aggregation=\"rate\"})",
     "legendFormat": "{{documenttype}}"
    }
   ]
  },
  { "title": "Documents", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Document count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (doctype) (label_replace({__name__=~\"vespa_searchnode_proton_doctypes_.*_numdocs\",aggregation=\"last\"}, \"doctype\", \"$1\", \"__name__\", \".*doctypes_(.*)_numdocs\"))",
     "legendFormat": "{{doctype}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg by (documenttype) (vespa_searchnode_content_proton_documentdb_ready_attribute_memory_usage_used_bytes{aggregation=\"last\"})",
     "legendFormat": "{{documenttype}} attribute"
    },
    {
     "expr": "avg by (documenttype) (vespa_searchnode_content_proton_documentdb_index_memory_usage_used_bytes{aggregation=\"last\"})",
     "legendFormat": "{{documenttype}} index"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by(documenttype) (vespa_searchnode_content_proton_documentdb_ready_document_store_disk_usage{aggregation=\"last\"})",
     "legendFormat": "{{documenttype}} store"
    },
    {
     "expr": "avg by (documenttype) (vespa_searchnode_content_proton_documentdb_index_disk_usage{aggregation=\"last\"})",
     "legendFormat": "{{documenttype}} index"
    }
   ]
  },
  { "title": "Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Heap usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "vespa_container_mem_heap_used{aggregation=\"last\"} / vespa_container_mem_heap_total{aggregation=\"last\"} ",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Feed operation rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum without (host) (vespa_container_feed_operations{aggregation=\"rate\"})",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  { "title": "Content", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Content Node (proton) memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "vespa_searchnode_proton_memoryusage{aggregation=\"average\"}",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Memory utilization in percent of memory limit",
   "type": "graph",
   "description": "Memory limit is normally 80% of total memory",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 47 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "vespa_searchnode_content_proton_resource_usage_memory_utilization{aggregation=\"average\"}",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Total documents in memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vespa_searchnode_proton_docsinmemory{aggregation=\"average\"}",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Disk utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "vespa_searchnode_content_proton_resource_usage_disk_utilization{aggregation=\"last\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Document count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(label_replace({__name__=~\"vespa_searchnode_proton_doctypes_.*_numdocs\",aggregation=\"last\"}, \"doctype\", \"$1\", \"__name__\", \".*doctypes_(.*)_numdocs\"))",
     "legendFormat": "{{ host }} {{ doctype }}"
    }
   ]
  }
 ]
}