mariadb:
  enabled: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: "monitoring"

elasticsearch:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: "monitoring"
elastic:
  enabled: false
  version: 8.6.1
  replicas: 1 #minimo 3 datanodes
  masterReplicas: 1
  name: ic4302
kibana:
  version: 8.6.1
  replicas: 1
  name: ic4302
prometheus-elasticsearch-exporter:
  env:
    ES_USERNAME: elastic
  extraEnvSecrets:
    ES_PASSWORD:
      secret: ic4302-es-elastic-user
      key: elastic
  es:
    uri: http://ic4302-es-http:9200
    cluster_settings: true
  serviceMonitor:
    enabled: true
    namespace: monitoring

redis:
  enabled: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: "monitoring"

memcached:
  enabled: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: "monitoring"

chromadb:
  allowReset: false
  isPersistent: true
  persistDirectory: /data
  logConfigFileLocation: /chroma/log_config.yaml
  logConfigMap: null
  logging:
    root: "INFO"
    chromadb: "DEBUG"
    uvicorn: "INFO"
  anonymizedTelemetry: false
  corsAllowOrigins: [] # as of version 1.0.x * is not allowed
  serverHost: "0.0.0.0"
  serverHttpPort: 8000
  maxPayloadSizeBytes: "41943040"
  data:
    volumeSize: "1Gi"
    storageClass: null
    accessModes: [ "ReadWriteOnce" ]
    retentionPolicyOnDelete: "Delete"
  telemetry:
    enabled: false
    endpoint: ""
    serviceName: "chroma"
  maintenance:
    collection_cache_policy: null # possible values: null or "LRU"
    collection_cache_limit_bytes: 1000000000 # defaults to 1GB. TODO: this must also observe limits if defined
  auth: # not working in 1.0.x
    enabled: false
