config:
  docker_registry: prosoli
  producer:
    replicas: 1
    name: web-spider
    image: web-spider
  consumer:
    replicas: 1
    name: downloader
    image: downloader
  debug:
    replicas: 1
    name: debug
    image: spark-job
  cronjob:
    name: spark-job
    image: spark-job
    schedule: "0 */12 * * *"