config:
  docker_registry: carayacn # docker registry replace with your own username
  controller:
    enabled: true
    replicas: 1
    name: controller
    image: controller
    schedule: "0 * * * *"  #every hour
  beautifulSoup:
    enabled: true
    replicas: 1
    name: beautiful-soup
    image: beautiful-soup
  sparkProcessorJob:
    enabled: true
    replicas: 1
    name: spark-processor-job
    image: spark-processor-job
    schedule: "0 * * * *"  # every hour
  spacyEntityExtractor:
    enabled: true
    replicas: 2
    name: spacy-entity-extractor
    image: spacy-entity-extractor