mongo:
  enabled: false
  config:
    namespace: default
    connectionString: databases-mongodb.default.svc.cluster.local:27017
    bucketName: ic-tec-dataset
    path: CARPETA_HCDCP_BACKUP/mongodb
    maxBackups: 3
    secret: databases-mongodb
    name: "202511230002"                   # Nombre de la copia de seguridad a descargar
    schedule: "0 */12 * * *"
    diskSize: 2
    storageClass: hostpath
    provider: aws
    type: backup

couchdb:
  enabled: true
  config:
    namespace: default
    connectionString: databases-couchdb.default.svc.cluster.local:5984
    bucketName: ic-tec-dataset
    path: CARPETA_HCDCP_BACKUP/couchdb
    maxBackups: 3
    secret: databases-couchdb
    name: couchdb
    schedule: "0 */12 * * *"
    diskSize: 2
    storageClass: hostpath
    provider: aws
    type: backup
    serviceAccount: default


mariadb:
  enabled: false
  config:
    namespace: default
    connectionString: databases-mariadb.default.svc.cluster.local:3306
    bucketName: ic-tec-dataset
    path: CARPETA_HCDCP_BACKUP/mariadb
    maxBackups: 3
    secret: databases-mariadb
    name: mariadb
    schedule: "0 */12 * * *"
    diskSize: 2Gi
    storageClass: hostpath
    provider: aws
    type: backup # backup o restore
    #name:  202511230123.sql # nombre del backup a restaurar
    serviceAccount: default

postgresql:
  enabled: false
  config:
    namespace: default
    connectionString: databases-postgresql.default.svc.cluster.local:5432   
    bucketName: ic-tec-dataset
    path: CARPETA_HCDCP_BACKUP/postgresql
    maxBackups: 3
    secret: databases-postgresql
    name: postgres
    schedule: "0 */12 * * *"
    diskSize: 2Gi
    storageClass: hostpath
    provider: aws
    type: backup # backup o restore
    # name: 202511232330.sql # nombre del backup a restaurar
    serviceAccount: default
