apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-initdb
data:
  promptsy.sql: |-
{{ .Files.Get "promptsy.sql" | indent 4 }}

  elastic-mappings.json: |-
{{ .Files.Get "elastic-mappings.json" | indent 4}}
