{{- if .Values.config.backend.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.config.backend.name }}-metrics
  labels:
    app: {{ .Values.config.backend.name }}
    release: prometheus
spec:
  ports:
    - name: metrics
      port: 5000
      targetPort: 5000
  selector:
    app: {{ .Values.config.backend.name }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.config.backend.name }}-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: {{ .Values.config.backend.name }}
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
{{- end }}
