apiVersion: v1
kind: Service
metadata:
  name: backend-ui-metrics
  labels:
    app: backend-ui
    release: prometheus
spec:
  selector:
    app: backend-ui       # debe coincidir con las labels de tus pods
  ports:
    - name: metrics
      protocol: TCP
      port: 5000          # puerto que Prometheus scrapea
      targetPort: 5000
---
# ServiceMonitor
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-ui-monitor
  namespace: monitoring
  labels:
    release: prometheus
    app: backend-ui
spec:
  selector:
    matchLabels:
      app: backend-ui
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s