mongodb:
  image:
    repository: bitnamilegacy/mongodb
  global:
    security:
      allowInsecureImages: true
  enabled: true
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
  extraEnvVars:
    - name: EXPERIMENTAL_DOCKER_DESKTOP_FORCE_QEMU
      value: "1"

#Apagar encender segun se use elaticsearch o opensearch
elastic:
  enabled: true
  version: 8.6.1
  replicas: 1
  name: ic4302
  fullnameOverride: mi-elasticsearch
kibana:
  enabled: true
  version: 8.6.1
  replicas: 1
  name: ic4302

opensearch:
  enabled: false
  fullnameOverride: "mi-opensearch"
  clusterName: "opensearch-cluster"
  replicas: 1
  extraEnvs:
    - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
      value: "BaseDatos12345!"
  keystore:
    - secretName: snapshot-secret
  plugins:
    enabled: true
    installList:
      - repository-s3


opensearchDashboards:
  enabled: false
  fullnameOverride: "mi-opensearch-dashboards"
  opensearchHosts:
    - "http://opensearch-cluster-master.default.svc.cluster.local:9200"

# MariaDB
mariadb:
  replicas: 1
  enabled: true
  image:
    registry: docker.io
    repository: bitnamilegacy/mariadb
    tag: 11.2.3-debian-11-r1

