mongodb:
  image:
    repository: bitnamilegacy/mongodb
  global:
    security:
      allowInsecureImages: true
  enabled: false
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
  extraEnvVars:
    - name: EXPERIMENTAL_DOCKER_DESKTOP_FORCE_QEMU
      value: "1"


#Apagar encender segun se use elaticsearch o opensearch
elastic:
  enabled: false
  version: 8.6.1
  replicas: 1
  name: ic4302
  fullnameOverride: mi-elasticsearch
kibana:
  enabled: false
  version: 8.6.1
  replicas: 1
  name: ic4302



opensearch:
  enabled: false
  fullnameOverride: "mi-opensearch"
  clusterName: "opensearch-cluster"
  replicas: 1
  extraEnvs:
    - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
      value: "BaseDatos12345!"
  keystore:
    - secretName: snapshot-secret
  plugins:
    enabled: true
    installList:
      - repository-s3


opensearchDashboards:
  enabled: false
  fullnameOverride: "mi-opensearch-dashboards"
  opensearchHosts:
    - "http://opensearch-cluster-master.default.svc.cluster.local:9200"


couchdb:
  enabled: true
  clusterSize: 1
  allowAdminParty: false
  createAdminSecret: true
  adminUsername: admin
  adminPassword: "Admin123!"                
  adminHash: ""            
  cookieAuthSecret: ""  
  image:
    repository: couchdb
    tag: 3.5.0
    pullPolicy: IfNotPresent
  service:
    enabled: true
    type: ClusterIP
    externalPort: 5984
    targetPort: 5984
  couchdbConfig:
    couchdb:
      uuid: "2f0e4cb63d984ea5b77b4b9a6fd43f19"
    chttpd:
      bind_address: any
      require_valid_user: false

# MariaDB
mariadb:
  replicas: 1
  enabled: false
  image:
    registry: docker.io
    repository: bitnamilegacy/mariadb
    tag: 11.2.3-debian-11-r1

# PostgreSQL
postgresql:
  replicas: 1
  enabled: false
  image:
    registry: docker.io
    repository: bitnamilegacy/postgresql
    tag: 15.5.0-debian-11-r1
