config:
    
    dataseeder: # Added configuration for DataSeeder
        enabled: true
        name: dataseeder
        replicas: 1
        image: prosoli/dataseeder # To charge with data the database
        openSearchEnable: false
        couchDBEnable: false
        mariaDBEnable: false
        elasticSearchEnable: false
        chromaDBEnable: false
        postgresEnable: false
        mongoEnable: true
