config:
  docker_registry: carayacn # docker registry replace with your own username
  backend:
    enabled: true
    replicas: 1
    name: backend
    image: backend_ui # backend image name, you have to replace the image by backend_ui_memcached if you want to use the backend with memcached
  frontend:
    replicas: 1
    name: frontend #this is the service name of frontend which represents the web application and the user interface
    image: frontend