config:
    flask: # Principal configuration for Flask app representing the app
        enabled: true
        name: flasktest
        replicas: 1
        image: prosoli/mariadb-memcached

    dataseeder: # Added configuration for DataSeeder
        enabled: true
        name: dataseeder
        replicas: 1
        image: prosoli/dataseeder # To charge with data the database


