config:
    flask: # Principal configuration for Flask app representing the app
        enabled: true
        name: flasktest
        replicas: 10 #coloquen 10 replicas para la prueba de carga, se debe tener en cuenta la capacidad
        image: helena0504/elasticsearch
        vespaEnable: false
        mariaDBEnable: false
        elasticSearchEnable: true
        chromaDBEnable: false
        postgresEnable: false

    dataseeder: # Added configuration for DataSeeder
        enabled: false
        name: dataseeder
        replicas: 1
        image: helena0504/dataseeder # To charge with data the database
        vespaEnable: false
        mariaDBEnable: false
        elasticSearchEnable: true
        chromaDBEnable: false
        postgresEnable: false
