FROM apache/spark:3.4.2
USER root

WORKDIR /app

COPY app/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app/app.py .
COPY app/functions.py .
COPY app/test.py .
# Run tests during image build using python3 (image provides python3 but not the 'python' symlink)
RUN python3 -m pytest test.py -v

CMD ["spark-submit","--master", "local[*]","--packages", "org.mongodb.spark:mongo-spark-connector_2.12:10.2.1","app.py"]