FROM apache/spark:3.4.2
USER root

WORKDIR /app

COPY app/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app/app.py .
COPY app/functions.py .
COPY app/test.py .
# Copiar el conector de MongoDB al directorio de jars de Spark
#COPY app/mongo-spark-connector_2.13-10.3.0.jar /opt/spark/jars/
#COPY app/mongodb-driver-sync-4.11.0.jar /opt/spark/jars/

# Ejecutar la aplicación con Spark y el conector: usar los JAR locales en /opt/spark/jars
# Evitar --packages para que no intente descargar de Maven en tiempo de ejecución
#CMD ["spark-submit","--master","local[*]","--jars","/opt/spark/jars/mongo-spark-connector_2.13-10.3.0.jar,/opt/spark/jars/mongodb-driver-sync-4.11.0.jar","app.py"]
RUN pytest -s -vv test.py

CMD ["spark-submit","--master", "local[*]","--packages", "org.mongodb.spark:mongo-spark-connector_2.12:10.2.1","app.py"]