{{- if .Values.config.beautifulSoup.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.config.beautifulSoup.name }}
  labels:
    app: {{ .Values.config.beautifulSoup.name }}
spec:
  replicas: {{ .Values.config.beautifulSoup.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.config.beautifulSoup.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.config.beautifulSoup.name }}
    spec:
      containers:
        - name: {{ .Values.config.beautifulSoup.name }}
          image: "{{ .Values.config.docker_registry }}/{{ .Values.config.beautifulSoup.image }}"

          env:
            - name: MONGO_URI
              value: "mongodb+srv://dbUser:B1b5xCdAOZDVfjcC@productssearch.sao2plc.mongodb.net/ecomm?appName=ProductsSearch"
            - name: INGESTION_COLLECTION
              value: "ingestion"

            - name: S3_BUCKET
              value: "ic-tec-dataset"

            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: AWS_ACCESS_KEY
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: AWS_SECRET_KEY
            - name: AWS_REGION
              value: "us-east-1"

            - name: RABBITMQ
              value: "databases-rabbitmq"
            - name: RABBITMQ_QUEUE_HTML
              value: "queue_parse"
            - name: RABBITMQ_QUEUE_ENTITY
              value: "queue_entity"
            - name: RABBITMQ_USER
              value: "user"
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: databases-rabbitmq
                  key: rabbitmq-password

            - name: SHARED_VOLUME_PATH
              value: "/app/data"

          volumeMounts:
            - name: shared-volume
              mountPath: /app/data/

      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: data
{{- end }}
