{{- if .Values.config.controller.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.config.controller.name }}
spec:
  schedule: "{{ .Values.config.controller.schedule }}"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        metadata:
          labels:
            app: {{ .Values.config.controller.name }}
        spec:
          restartPolicy: OnFailure
          containers:
            - name: {{ .Values.config.controller.name }}
              image: {{ .Values.config.docker_registry }}/{{ .Values.config.controller.image }}
              ports:
                - name: metrics
                  containerPort: 8000
              env:
                - name: S3_BUCKET
                  value: "ic-tec-dataset"
                - name: S3_PREFIXES
                  value: "CARPETA_HCDCP/"
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: aws-secret
                      key: AWS_ACCESS_KEY
                      optional: false
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: aws-secret
                      key: AWS_SECRET_KEY
                      optional: false
                - name: AWS_REGION
                  value: "us-east-1"

                - name: RABBITMQ
                  value: "databases-rabbitmq"
                - name: RABBITMQ_QUEUE_PARSE
                  value: "queue_parse"
                - name: RABBITMQ_USER
                  value: "user"
                - name: RABBITMQ_PASS
                  valueFrom:
                    secretKeyRef:
                      name: databases-rabbitmq
                      key: rabbitmq-password
                      optional: false
{{- end }}
