apiVersion: v1
kind: Pod
metadata:
  name: spark-loader
spec:
  restartPolicy: Never
  containers:
    - name: loader
      image: bitnami/kubectl:latest
      command: ["sleep", "3600"]
      volumeMounts:
        - name: data
          mountPath: /app/data/
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: data