{{- if .Values.config.spacyEntityExtractor.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.config.spacyEntityExtractor.name }}
  labels:
    app: {{ .Values.config.spacyEntityExtractor.name }}
spec:
  replicas: {{ .Values.config.spacyEntityExtractor.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.config.spacyEntityExtractor.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.config.spacyEntityExtractor.name }}
    spec:
      containers:
        - name: {{ .Values.config.spacyEntityExtractor.name }}
          image: "{{ .Values.config.docker_registry }}/{{ .Values.config.spacyEntityExtractor.image }}"
          env:
            - name: MONGO_URI
              value: "mongodb+srv://dbUser:B1b5xCdAOZDVfjcC@productssearch.sao2plc.mongodb.net/ecomm?appName=ProductsSearch"
            - name: INGESTION_COLLECTION
              value: "ingestion"
            
            - name: RABBITMQ
              value: "databases-rabbitmq"
            - name: RABBITMQ_QUEUE
              value: "queue_entity"
            - name: RABBITMQ_USER
              value: "user"
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: databases-rabbitmq
                  key: rabbitmq-password
                  optional: false

            # Datos para leer y escribir
            - name: BASE_PATH
              value: "/app/data"
          volumeMounts:
            - name: data-volume
              mountPath: /app/data/

      # Volumen
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: data
{{- end }}
