{{- if .Values.config.sparkProcessorJob.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.config.sparkProcessorJob.name }}
spec:
  schedule: "{{ .Values.config.sparkProcessorJob.schedule }}"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        metadata:
          labels:
            app: {{ .Values.config.sparkProcessorJob.name }}
        spec:
          restartPolicy: OnFailure
          containers:
            - name: {{ .Values.config.sparkProcessorJob.name }}
              image: {{ .Values.config.docker_registry }}/{{ .Values.config.sparkProcessorJob.image }}
              env:
                - name: S3_BUCKET
                  value: "ic-tec-dataset"
                - name: URI_MONGODB
                  value: "mongodb+srv://dbUser:B1b5xCdAOZDVfjcC@productssearch.sao2plc.mongodb.net/ecomm.documents?appName=ProductsSearch"
                - name: VOLUMEN_PVC
                  value: "/app/data/augmented"
                - name: S3_PREFIXES
                  value: "amazon-books,amazon-book-reviews"
                - name: AWS_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: aws-secret
                      key: AWS_ACCESS_KEY
                      optional: false
                - name: AWS_SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: aws-secret
                      key: AWS_SECRET_KEY
                      optional: false
                - name: AWS_REGION
                  value: "us-east-1"
                - name: SPARK_EXECUTOR_MEMORY
                  value: "3g"
                - name: SPARK_DRIVER_MEMORY
                  value: "2g"
                - name: SPARK_SQL_SHUFFLE_PARTITIONS
                  value: "24"
              volumeMounts:
                - name: data
                  mountPath: /app/data/
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: data
{{- end }}
