apiVersion: v1
kind: PersistentVolume
metadata:
  name: augmented-pvc
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  hostPath:
    path: /run/desktop/mnt/host/c/Users/chris/k8s-data #editar según preferencia
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: augmented-pvc
spec:
  volumeName: augmented-pvc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: manual

