apiVersion: v1
kind: PersistentVolume
metadata:
  name: augmented-pvc
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /run/desktop/mnt/host/c/Users/caray/k8s-data
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: augmented-pvc
spec:
  volumeName: augmented-pvc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: manual