config:
  docker_registry: helena0504
  producer:
    replicas: 1
    name: web-spider
    image: web-spider
    schedule: "0 */12 * * *"
  consumer:
    replicas: 1
    name: downloader
    image: downloader
  debug:
    replicas: 1
    name: debug
    image: spark-job
  cronjob:
    name: spark-job
    image: spark-job
    schedule: "0 */12 * * *"